-- TODO: 13 - Add seed data for the orders table
--  INSERT INTO orders (description, status, total_amount, customer_email, order_date, internal_notes)
--  VALUES ('Laptop', 'PENDING', 999.99, 'john@mail.com', '2024-01-15', 'rush delivery');
--  Add at least 3 more rows with different statuses
